server:
  port: 5001

spring:
  application:
    name: USER-SERVICE

  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    password: Bn19c0248@
    username: root
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/task_user_service
    driver-class-name: com.mysql.cj.jdbc.Driver
